"""added quatity to recip_ingred

Revision ID: 27861e048c64
Revises: 95d77e1554ae
Create Date: 2018-07-08 23:04:20.210849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27861e048c64'
down_revision = '95d77e1554ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingreds', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingreds', 'quantity')
    # ### end Alembic commands ###
