"""new database with relationships

Revision ID: 95d77e1554ae
Revises: 
Create Date: 2018-07-08 21:47:14.430643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d77e1554ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating')
    )
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=True)
    op.create_table('creature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creature_name'), 'creature', ['name'], unique=True)
    op.create_table('recipe_ingreds',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingred_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingred_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.create_table('creature_recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('creature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creature.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creature_recipe')
    op.drop_table('recipe_ingreds')
    op.drop_index(op.f('ix_creature_name'), table_name='creature')
    op.drop_table('creature')
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
