"""new and imporved association class test

Revision ID: b179e67cd8b6
Revises: 27861e048c64
Create Date: 2018-07-09 21:08:57.020401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b179e67cd8b6'
down_revision = '27861e048c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingred_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingred_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingred_id')
    )
    op.drop_table('recipe_ingreds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingreds',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('ingred_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingred_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.drop_table('association')
    # ### end Alembic commands ###
